bot:
  prefix: "!"
  description: "A Discord bot that sends catgirls and anime gifs"

cooldown:
  global: 3600  # Global cooldown in seconds

reactions:
  pat:
    - "pat"
    - "pet"
    - "pats"
  hug:
    - "hug"
    - "hugs"
    - "cuddle"
    - "glomp"
  baka:
    - "stupid"
    - "dumb"
    - "idiot"
    - "baka"
  cringe:
    - "embarass"
    - "embarassing"
    - "cringe"
    - "cringey"
  gecg:
    - "gecg"
    - "not like the other girls"
    - "made in a lab"
  trap:
    - "trap"
    - "tranny"

apis:
  nekos_life:
    base_url: "https://nekos.life/api/v2"
    endpoints:
      pat: "/img/pat"
      hug: "/img/hug"
      kiss: "/img/kiss"
      baka: "/img/baka"
      gecg: "/img/gecg"
  waifu_pics:
    base_url: "https://api.waifu.pics"
    endpoints:
      pat: "/sfw/pat"
      hug: "/sfw/glomp"
      kiss: "/sfw/kiss"
      baka: "/sfw/bully"
      cringe: "/sfw/cringe"
      trap: "/nsfw/trap"